"""Regenerate the self-hosted font files in this folder. See README.md.

usage: python make-fonts.py <path to Inter[opsz,wght].ttf> <path to PlusJakartaSans[wght].ttf>

Needs `pip install fonttools brotli`. Cuts each google/fonts variable file into the same
unicode-range subsets Google Fonts serves, and writes the @font-face rules for every subset
except "latin" (that one goes through next/font/local so Next can preload it).
"""

import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))

# Google Fonts' own subset ranges (fonts.googleapis.com/css2, October 2026), in Google's order.
RANGES = {
    "cyrillic-ext": "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
    "cyrillic": "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
    "greek-ext": "U+1F00-1FFF",
    "greek": "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF",
    "vietnamese": "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0,"
    " U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB",
    "latin-ext": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308,"
    " U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113,"
    " U+2C60-2C7F, U+A720-A7FF",
    "latin": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308,"
    " U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
}

# Google's latin file also carries these combining marks so accented letters can be composed.
EXTRA_GLYPHS = {"latin": "U+0300-0301, U+0303, U+0309, U+0323"}

FAMILIES = [
    # (CSS family, file prefix, weight descriptor, subsets Google serves for the family,
    #  OpenType features Google keeps in its files). Keeping only Google's features keeps the
    #  files as small as Google's and means no alternate glyph appears that did not before.
    ("Inter", "inter", "100 900",
     ["cyrillic-ext", "cyrillic", "greek-ext", "greek", "vietnamese", "latin-ext", "latin"],
     "calt,ccmp,dnom,frac,kern,locl,mark,mkmk,numr,pnum,tnum"),
    # The consoles only ever asked Google for 600 and 700.
    ("Plus Jakarta Sans", "plus-jakarta-sans", "600 700",
     ["cyrillic-ext", "vietnamese", "latin-ext", "latin"],
     "calt,ccmp,dnom,frac,kern,liga,locl,mark,numr,pnum,tnum"),
]


# The metric-matched Arial fallback next/font/google 15.5 generated for each family (its own
# metrics table). Written here rather than computed by next/font/local, whose figures differ a
# little, so text takes the same space while the real font loads.
FALLBACKS = {
    "Inter": ("90.44%", "22.52%", "0.00%", "107.12%"),
    "Plus Jakarta Sans": ("98.88%", "21.15%", "0.00%", "104.98%"),
}


def run(*args):
    # fontTools stamps "modified" with the current time unless SOURCE_DATE_EPOCH is set; fix it
    # (google/fonts Inter commit date) so rerunning the script gives byte-identical files.
    env = dict(os.environ, SOURCE_DATE_EPOCH=os.environ.get("SOURCE_DATE_EPOCH", "1772556323"))
    subprocess.run([sys.executable, "-m", *args], check=True, env=env)


def main(inter_ttf, jakarta_ttf):
    with tempfile.TemporaryDirectory() as tmp:
        # Google serves Inter with the optical-size axis pinned at its default (14) when a page
        # asks only for weights, as ours did. Pin it the same way so text sets identically.
        inter_pinned = os.path.join(tmp, "inter-opsz14.ttf")
        run("fontTools.varLib.instancer", inter_ttf, "opsz=14", "-q", "-o", inter_pinned)
        sources = {"inter": inter_pinned, "plus-jakarta-sans": jakarta_ttf}

        for family, prefix, weight, subsets, features in FAMILIES:
            css = [
                "/*",
                f"  {family}: every Google Fonts subset except latin, which next/font/local loads",
                "  (and preloads) from ../src/fonts, plus its size-matched fallback face.",
                "  Generated by make-fonts.py; do not edit by hand.",
                "*/",
            ]
            ascent, descent, line_gap, size = FALLBACKS[family]
            css += [
                "@font-face {",
                f"  font-family: '{family} Fallback';",
                "  src: local('Arial');",
                f"  ascent-override: {ascent};",
                f"  descent-override: {descent};",
                f"  line-gap-override: {line_gap};",
                f"  size-adjust: {size};",
                "}",
            ]
            for subset in subsets:
                out = f"{prefix}-{subset}.woff2"
                unicodes = RANGES[subset] + (", " + EXTRA_GLYPHS[subset] if subset in EXTRA_GLYPHS else "")
                run(
                    "fontTools.subset", sources[prefix],
                    "--unicodes=" + unicodes.replace(" ", ""),
                    "--layout-features=" + features, "--name-IDs=*", "--name-languages=*",
                    "--notdef-outline", "--flavor=woff2",
                    "--output-file=" + os.path.join(HERE, out),
                )
                if subset == "latin":
                    continue
                css += [
                    f"/* {subset} */",
                    "@font-face {",
                    f"  font-family: '{family}';",
                    "  font-style: normal;",
                    f"  font-weight: {weight};",
                    "  font-display: swap;",
                    f"  src: url('./{out}') format('woff2');",
                    f"  unicode-range: {RANGES[subset]};",
                    "}",
                ]
            with open(os.path.join(HERE, f"{prefix}.css"), "w", encoding="ascii", newline="\n") as f:
                f.write("\n".join(css) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
