import { HttpStatus, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash, randomBytes } from 'node:crypto';
import * as bcrypt from 'bcryptjs';
import { NotificationType, OrganizationStatus, Role } from '@eticketsgo/shared-types';
import type {
  CreateOrganizationInput,
  AcceptInvitationInput,
  InviteMemberInput,
  ReviewDecisionInput,
  UpdateOrganizationLegalIdentityInput,
  UpdateOrganizationProfileInput,
} from '@eticketsgo/validation';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { AdminAudienceService } from '../notifications/admin-audience.service';
import { OrgAccessService } from '../tenancy/org-access.service';
import { AppException, ErrorCodes } from '../common/errors';
import type { RequestUser } from '../common/decorators';

/**
 * How long an invitation stays valid: seven days.
 *
 * Long enough to survive a weekend, short enough that a link sitting in an inbox or a chat
 * log does not remain a live credential indefinitely.
 */
const INVITATION_TTL_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Marks a password hash that was generated BY an invitation rather than chosen by a person.
 *
 * Such an account has no credential anybody can present, and must not be treated as one that
 * merely forgot its password. The prefix makes that a stored fact rather than an inference.
 */
const INVITE_PLACEHOLDER_PREFIX = 'invite-pending$';

/** Which console an invitee belongs in, and how to find its URL. */
type ConsoleKind = 'organizer' | 'admin';
const CONSOLES: Record<ConsoleKind, { variable: string; devPort: number }> = {
  organizer: { variable: 'ORGANIZER_WEB_URL', devPort: 3001 },
  admin: { variable: 'ADMIN_WEB_URL', devPort: 3002 },
};

function slugify(name: string): string {
  return `${name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')}-${randomBytes(3).toString('hex')}`;
}

@Injectable()
export class OrganizationsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly access: OrgAccessService,
    private readonly audit: AuditService,
    private readonly audience: AdminAudienceService,
    private readonly config: ConfigService,
  ) {}

  async register(user: RequestUser, input: CreateOrganizationInput) {
    const org = await this.prisma.organization.create({
      data: {
        name: input.name,
        slug: slugify(input.name),
        contactEmail: input.contactEmail,
        status: OrganizationStatus.PENDING,
        members: { create: { userId: user.id, role: Role.ORGANIZER_OWNER } },
      },
    });

    // Grant the platform organizer role if the user does not have it yet.
    if (!user.roles.includes(Role.ORGANIZER_OWNER)) {
      await this.prisma.user.update({
        where: { id: user.id },
        data: { roles: { set: [...new Set([...user.roles, Role.ORGANIZER_OWNER])] } },
      });
    }

    await this.audit.record({
      actorUserId: user.id,
      organizationId: org.id,
      action: 'ORGANIZATION_CREATED',
      entityType: 'Organization',
      entityId: org.id,
    });

    /*
      Tell the admins something is waiting.

      A new organization is PENDING and cannot sell a ticket until a human approves it. The
      audit entry above recorded that it happened; nothing told anyone to look. So an
      organizer signed up, saw "awaiting approval", and waited on a queue no one had been
      paged about.

      Never throws — see AdminAudienceService. The organization is committed by this point
      and losing it to a mail outage would be far worse than a missed email.
    */
    await this.audience.notifyAdmins(NotificationType.ORGANIZATION_REGISTERED, {
      organizationId: org.id,
      organizationName: org.name,
      contactEmail: org.contactEmail ?? user.email,
      registeredByUserId: user.id,
    });

    return org;
  }

  async listMine(user: RequestUser) {
    const ids = await this.access.managedOrganizationIds(user);
    return this.prisma.organization.findMany({
      where: ids ? { id: { in: ids } } : {},
      orderBy: { createdAt: 'desc' },
      include: { _count: { select: { members: true, events: true, venues: true } } },
    });
  }

  async get(user: RequestUser, id: string) {
    await this.access.assertMember(user, id);
    const org = await this.prisma.organization.findUnique({
      where: { id },
      include: { _count: { select: { members: true, events: true, venues: true } } },
    });
    if (!org)
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);
    return org;
  }

  /**
   * Update the public organizer profile (WS6). Only owners/managers may edit.
   * Empty-string fields clear (set to null); omitted fields are left unchanged.
   * `verified` is intentionally not editable here — it is an admin-set badge.
   */
  async updateProfile(user: RequestUser, id: string, input: UpdateOrganizationProfileInput) {
    await this.access.assertMember(user, id, [Role.ORGANIZER_OWNER, Role.ORGANIZER_MANAGER]);
    const data: Record<string, string | null> = {};
    for (const [key, value] of Object.entries(input) as [string, string | undefined][]) {
      if (value === undefined) continue;
      data[key] = value === '' ? null : value;
    }
    const updated = await this.prisma.organization.update({
      where: { id },
      data,
      include: { _count: { select: { members: true, events: true, venues: true } } },
    });
    await this.audit.record({
      actorUserId: user.id,
      organizationId: id,
      action: 'ORGANIZATION_PROFILE_UPDATED',
      entityType: 'Organization',
      entityId: id,
      metadata: { fields: Object.keys(data) },
    });
    return updated;
  }

  /**
   * Update the seller's legal + tax identity.
   *
   * Restricted to the OWNER, unlike the public profile a manager can edit. These fields are
   * printed on financial documents and reported against payouts — changing a tax
   * registration number is a materially different act from changing a bio, and is audited
   * with the old and new values so a later dispute can be reconstructed.
   */
  async updateLegalIdentity(
    user: RequestUser,
    id: string,
    input: UpdateOrganizationLegalIdentityInput,
  ) {
    await this.access.assertMember(user, id, [Role.ORGANIZER_OWNER]);
    const before = await this.prisma.organization.findUnique({
      where: { id },
      select: { legalName: true, taxRegistrationKind: true, taxRegistrationNumber: true },
    });
    const data: Record<string, string | null> = {};
    for (const [key, value] of Object.entries(input) as [string, string | undefined][]) {
      if (value === undefined) continue;
      data[key] = value === '' ? null : value;
    }
    const updated = await this.prisma.organization.update({ where: { id }, data });
    await this.audit.record({
      actorUserId: user.id,
      organizationId: id,
      action: 'ORGANIZATION_LEGAL_IDENTITY_UPDATED',
      entityType: 'Organization',
      entityId: id,
      metadata: {
        fields: Object.keys(data),
        // Documents already issued keep the old values — they are snapshots. Recording the
        // change here is what lets anyone explain why two invoices name the seller
        // differently.
        previousTaxRegistrationNumber: before?.taxRegistrationNumber ?? null,
        newTaxRegistrationNumber: updated.taxRegistrationNumber ?? null,
      },
    });
    return updated;
  }

  /**
   * The same edit, made by a platform administrator instead of the organizer's owner.
   *
   * ── WHY THIS IS A SEPARATE METHOD AND NOT A LOOSENED GUARD ─────────────────────────
   * The obvious change was to widen `updateLegalIdentity`'s role check to admit admins.
   * That would have been wrong in a way that only shows up later: the audit entry says who
   * acted but not on whose authority, and "the owner recorded their GSTIN" and "the platform
   * recorded a GSTIN on the organizer's behalf" are different facts about a number printed
   * on a tax invoice. If the number turns out to be wrong, which of those it was decides
   * whose mistake it is.
   *
   * So this records a distinct action, and carries `onBehalfOf` so a later reader can tell
   * the two apart without inferring it from the actor's role at read time — roles change.
   *
   * ── WHY AN ADMIN NEEDS THIS AT ALL ────────────────────────────────────────────────
   * During a pilot the platform onboards organizers directly: it collects the registration
   * on a call and enters it. Requiring the owner to sign in and self-serve first would mean
   * every early invoice goes out as a plain receipt rather than a tax invoice, and a receipt
   * cannot be reissued as one after the fact — the document is a snapshot.
   */
  async adminUpdateLegalIdentity(
    admin: RequestUser,
    id: string,
    input: UpdateOrganizationLegalIdentityInput,
  ) {
    const before = await this.prisma.organization.findUnique({
      where: { id },
      select: { legalName: true, taxRegistrationKind: true, taxRegistrationNumber: true },
    });
    if (!before) {
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);
    }

    const data: Record<string, string | null> = {};
    for (const [key, value] of Object.entries(input) as [string, string | undefined][]) {
      if (value === undefined) continue;
      data[key] = value === '' ? null : value;
    }
    const updated = await this.prisma.organization.update({ where: { id }, data });

    await this.audit.record({
      actorUserId: admin.id,
      organizationId: id,
      action: 'ORGANIZATION_LEGAL_IDENTITY_UPDATED_BY_ADMIN',
      entityType: 'Organization',
      entityId: id,
      metadata: {
        onBehalfOf: id,
        fields: Object.keys(data),
        // Documents already issued keep the old values — they are snapshots. Recording the
        // change is what lets anyone explain why two invoices name the seller differently.
        previousTaxRegistrationNumber: before.taxRegistrationNumber ?? null,
        newTaxRegistrationNumber: updated.taxRegistrationNumber ?? null,
      },
    });
    return updated;
  }

  /** The tax-invoice readiness of one organization, read by a platform administrator. */
  async adminLegalIdentityStatus(id: string) {
    const org = await this.prisma.organization.findUnique({
      where: { id },
      select: {
        legalName: true,
        taxRegistrationKind: true,
        taxRegistrationNumber: true,
        registeredAddressLine1: true,
        registeredAddressLine2: true,
        registeredCity: true,
        registeredRegion: true,
        registeredPostalCode: true,
        registeredCountry: true,
        financeContactName: true,
        financeContactEmail: true,
        financeContactPhone: true,
      },
    });
    if (!org) {
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);
    }
    const missing = (
      [
        ['legalName', 'Registered legal name'],
        ['registeredAddressLine1', 'Registered address'],
        ['registeredCity', 'City'],
        ['registeredCountry', 'Country'],
        ['financeContactEmail', 'Finance contact email'],
      ] as const
    )
      .filter(([field]) => !org[field])
      .map(([, label]) => label);

    return {
      ...org,
      missing,
      canIssueTaxInvoice: Boolean(org.taxRegistrationNumber?.trim()) && missing.length === 0,
    };
  }

  /**
   * What is still missing before this organization can issue a tax invoice.
   *
   * Reports the gap; does not decide policy. Whether an organizer is ALLOWED to sell without
   * a tax registration is a launch decision for each market, not something this method
   * asserts — it only says truthfully what is and is not on file.
   */
  async legalIdentityStatus(user: RequestUser, id: string) {
    await this.access.assertMember(user, id);
    const org = await this.prisma.organization.findUnique({
      where: { id },
      select: {
        legalName: true,
        taxRegistrationKind: true,
        taxRegistrationNumber: true,
        registeredAddressLine1: true,
        registeredCity: true,
        registeredCountry: true,
        financeContactEmail: true,
      },
    });
    if (!org) {
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);
    }
    const missing = (
      [
        ['legalName', 'Registered legal name'],
        ['registeredAddressLine1', 'Registered address'],
        ['registeredCity', 'City'],
        ['registeredCountry', 'Country'],
        ['financeContactEmail', 'Finance contact email'],
      ] as const
    )
      .filter(([field]) => !org[field])
      .map(([, label]) => label);

    return {
      ...org,
      canIssueTaxInvoice: Boolean(org.taxRegistrationNumber?.trim()) && missing.length === 0,
      missing,
    };
  }

  async listMembers(user: RequestUser, orgId: string) {
    await this.access.assertMember(user, orgId, [Role.ORGANIZER_OWNER, Role.ORGANIZER_MANAGER]);
    return this.prisma.organizationMember.findMany({
      where: { organizationId: orgId },
      include: { user: { select: { id: true, email: true, fullName: true } } },
      orderBy: { createdAt: 'asc' },
    });
  }

  /**
   * Add somebody to the team and give them a way in.
   *
   * -- WHAT WAS BROKEN ---------------------------------------------------------------
   * This created an OrganizationMember at status INVITED and stopped. Nothing anywhere
   * moved a member to ACTIVE, and `assertMember` refuses anything that is not ACTIVE, so
   * every person ever invited was locked out of the organization they had just joined.
   *
   * For an invitee with no prior account it was worse. A User row was created with a
   * RANDOM password, which nobody could ever know. Self-registration then failed with
   * "email already registered", and there is no password-reset flow, so that address was
   * permanently unusable. The invite bricked it.
   *
   * -- WHAT REPLACES IT --------------------------------------------------------------
   * An invitation the person can actually accept: single-use, hashed at rest, expiring.
   * Accepting is what sets the password (when they need one) and what moves the member to
   * ACTIVE. Until then they have no access, which is the correct default -- being named by
   * somebody else is not consent.
   *
   * The link is RETURNED TO THE CALLER, and also sent by email. Returning it matters more
   * than it looks: `EMAIL_PROVIDER=log` swallows mail silently in every environment set up
   * so far, and an invitation that depends on infrastructure the operator has not configured
   * yet is the same dead end wearing a new costume. Handing the owner a link they can send
   * themselves works everywhere, today.
   */
  async inviteMember(user: RequestUser, orgId: string, input: InviteMemberInput) {
    await this.access.assertMember(user, orgId, [Role.ORGANIZER_OWNER]);

    /*
      Resolved first, before anything is written.

      It throws when the environment cannot produce a reachable link, and doing that after
      creating the member would leave a person listed on the team with no invitation and no
      way in — the exact state this whole change exists to remove, reintroduced by the error
      path. Nothing is created unless the invitation can actually be delivered.
    */
    this.consoleBaseUrl('organizer');

    let invitee = await this.prisma.user.findUnique({ where: { email: input.email } });
    const isNewAccount = !invitee;
    if (!invitee) {
      /*
        Still a random password, and still unknowable -- but now that is the POINT rather
        than an accident. The account cannot be signed into until the invitation is
        accepted, and accepting is what sets a password the person chose. An account with no
        usable credential and no route to one was the bug; an account with no usable
        credential and an invitation waiting is simply a pending signup.
      */
      /*
        Prefixed so the accept path can tell "never had a password" from "has one they
        chose". Inferring it from hash shape would be a guess; a marker is a fact. bcrypt
        never produces this prefix, so it cannot collide with a real hash, and it is not a
        valid bcrypt string — which means `bcrypt.compare` can never match it and this
        account cannot be signed into until the invitation is accepted.
      */
      const passwordHash = `${INVITE_PLACEHOLDER_PREFIX}${await bcrypt.hash(
        randomBytes(32).toString('hex'),
        10,
      )}`;
      invitee = await this.prisma.user.create({
        data: {
          email: input.email,
          fullName: input.email.split('@')[0],
          passwordHash,
          roles: [Role.CUSTOMER],
        },
      });
    }

    const existing = await this.prisma.organizationMember.findUnique({
      where: { organizationId_userId: { organizationId: orgId, userId: invitee.id } },
    });
    if (existing) {
      throw new AppException(
        ErrorCodes.CONFLICT,
        'This person is already a team member.',
        HttpStatus.CONFLICT,
      );
    }

    const member = await this.prisma.organizationMember.create({
      data: { organizationId: orgId, userId: invitee.id, role: input.role, status: 'INVITED' },
      include: { user: { select: { id: true, email: true, fullName: true } } },
    });
    await this.audit.record({
      actorUserId: user.id,
      organizationId: orgId,
      action: 'MEMBER_INVITED',
      entityType: 'OrganizationMember',
      entityId: member.id,
      metadata: { role: input.role },
    });

    const inviteUrl = await this.issueInvitation(invitee.id, user.id, member.id);
    return { ...member, inviteUrl, needsPassword: isNewAccount };
  }

  /**
   * Mint (or replace) somebody's invitation and return the link to send them.
   *
   * Public because the back-office staff screen needs exactly this and must not grow its
   * own copy — a second invitation mechanism would be a second place for the token rules,
   * the expiry and the localhost guard to drift.
   *
   * Replacing rather than reusing: a resend must invalidate whatever went before, or an old
   * link forwarded to the wrong person still works. One live invitation per account, which
   * the unique key on `userId` enforces rather than merely encourages.
   */
  async issueInvitation(
    userId: string,
    invitedByUserId: string,
    organizationMemberId?: string,
    console: ConsoleKind = 'organizer',
  ): Promise<string> {
    const token = randomBytes(32).toString('base64url');
    const tokenHash = createHash('sha256').update(token).digest('hex');
    const expiresAt = new Date(Date.now() + INVITATION_TTL_MS);

    await this.prisma.accountInvitation.upsert({
      where: { userId },
      create: { userId, organizationMemberId, tokenHash, expiresAt, invitedByUserId },
      update: {
        tokenHash,
        expiresAt,
        invitedByUserId,
        acceptedAt: null,
        // Repointed, not merged: a second invitation to the same person supersedes the
        // first, and leaving a stale membership attached would activate the wrong thing.
        organizationMemberId: organizationMemberId ?? null,
      },
    });

    return `${this.consoleBaseUrl(console)}/invite/${token}`;
  }

  /**
   * Where the invitee should be sent, or a refusal that names the missing variable.
   *
   * Which console matters. A back-office invitee sent to the ORGANIZER app would set their
   * password in a product they have no account in and then be told to sign in somewhere
   * they have not been shown — so the link goes to the console the invitation is for.
   *
   * The localhost fallback is right for a laptop and catastrophic anywhere else: QA handed
   * out `http://localhost:3001/invite/<token>` for its first hour, which is a link nobody
   * but the developer can open. It failed silently — the invitation was real, the token was
   * valid, and the recipient simply could not reach it.
   *
   * So the fallback applies only where it is true. Anywhere else this throws, because an
   * error naming the variable is recoverable in a minute, and a dead link sent to a new
   * colleague is not recoverable at all — nobody finds out until they ask why they never
   * got in.
   *
   * Keyed on APP_ENV, not NODE_ENV: QA and UAT both run NODE_ENV=production, so NODE_ENV
   * cannot tell a deployment from a laptop, and this codebase has been caught by that before.
   */
  private consoleBaseUrl(kind: ConsoleKind): string {
    const { variable, devPort } = CONSOLES[kind];
    const configured = this.config.get<string>(variable)?.trim();
    if (configured) return configured.replace(/\/+$/, '');

    const appEnv = this.config.get<string>('APP_ENV') ?? 'LOCAL';
    if (['LOCAL', 'DEV'].includes(appEnv)) return `http://localhost:${devPort}`;

    throw new AppException(
      ErrorCodes.INTERNAL,
      `Invitations cannot be sent: ${variable} is not configured, so the link would point at localhost. Set it to the ${kind} console URL for this environment.`,
      HttpStatus.INTERNAL_SERVER_ERROR,
      { appEnv, variable },
    );
  }

  /**
   * What an invitation looks like to the person holding the link, before they commit.
   *
   * Public and unauthenticated by necessity — the whole point is that the invitee may have
   * no account yet. It returns only what the page must render: who invited them, to what,
   * and whether they need to choose a password. Never the token, never anything about the
   * organization beyond its name.
   */
  async describeInvitation(token: string) {
    const invitation = await this.loadInvitation(token);
    return {
      email: invitation.user.email,
      /*
        Back-office invitations belong to no organization. Saying "the ETicketsGo back
        office" is the truth for them; inventing an organization name would not be.
      */
      organizationName:
        invitation.organizationMember?.organization.name ?? 'the ETicketsGo back office',
      role: invitation.organizationMember?.role ?? 'BACK_OFFICE',
      /*
        Whether to ask for a password. An invitee who already had an account keeps the
        password they know; asking them to set a new one would let anybody holding a
        forwarded link change the credentials of an existing user.
      */
      needsPassword: !invitation.hasUsablePassword,
      expiresAt: invitation.expiresAt,
    };
  }

  /**
   * Accept an invitation: this is the ONLY thing that moves a member to ACTIVE.
   *
   * Deliberately not something an owner can do on the invitee's behalf. Being added to a
   * team is a change to somebody else's account, and the token is how they consent to it.
   */
  async acceptInvitation(token: string, input: AcceptInvitationInput) {
    const invitation = await this.loadInvitation(token);
    const { user: account, organizationMember: member } = invitation;

    if (!invitation.hasUsablePassword && !input.password) {
      throw new AppException(
        ErrorCodes.VALIDATION_FAILED,
        'Choose a password to finish setting up your account.',
        HttpStatus.BAD_REQUEST,
      );
    }

    const userUpdate: { passwordHash?: string; fullName?: string } = {};
    if (!invitation.hasUsablePassword && input.password) {
      userUpdate.passwordHash = await bcrypt.hash(input.password, 10);
      // The placeholder name is the email's local part, set when the invite created the
      // account. Replace it only if they gave us something real.
      if (input.fullName?.trim()) userUpdate.fullName = input.fullName.trim();
    }

    await this.prisma.$transaction(async (tx) => {
      if (Object.keys(userUpdate).length > 0) {
        await tx.user.update({ where: { id: account.id }, data: userUpdate });
      }
      // Only when the invitation carried one. A back-office invitation activates the
      // account itself; its capabilities were granted when it was sent.
      if (member) {
        await tx.organizationMember.update({
          where: { id: member.id },
          data: { status: 'ACTIVE' },
        });
      }
      /*
        Marked accepted rather than deleted, so the row keeps who invited whom and when.

        `acceptedAt` is what makes the link single-use — `loadInvitation` refuses any
        invitation carrying it, and a test proves that by removing the rotation below and
        watching reuse still fail. The rotation earns its place for a different reason: once
        spent, the token's hash is no longer in the table at all, so somebody who later
        obtains a copy of the link cannot even confirm which invitation it belonged to.
      */
      await tx.accountInvitation.update({
        where: { id: invitation.id },
        data: { acceptedAt: new Date(), tokenHash: `accepted:${invitation.id}` },
      });
    });

    await this.audit.record({
      actorUserId: account.id,
      organizationId: member?.organizationId,
      action: member ? 'MEMBER_INVITE_ACCEPTED' : 'BACK_OFFICE_INVITE_ACCEPTED',
      entityType: member ? 'OrganizationMember' : 'User',
      entityId: member?.id ?? account.id,
      metadata: member ? { role: member.role } : {},
    });

    return {
      email: account.email,
      organizationId: member?.organizationId ?? null,
      organizationName: member?.organization.name ?? 'the ETicketsGo back office',
      role: member?.role ?? 'BACK_OFFICE',
    };
  }

  /**
   * Resolve a token to a live invitation, or refuse with a reason the holder can act on.
   *
   * One deliberate imprecision: an unknown token and an already-accepted one give the same
   * answer. Distinguishing them would let somebody probe which invitations exist.
   */
  private async loadInvitation(token: string) {
    const tokenHash = createHash('sha256').update(token).digest('hex');
    const invitation = await this.prisma.accountInvitation.findUnique({
      where: { tokenHash },
      include: {
        user: { select: { id: true, email: true, fullName: true, passwordHash: true } },
        organizationMember: { include: { organization: { select: { name: true } } } },
      },
    });

    if (!invitation || invitation.acceptedAt) {
      throw new AppException(
        ErrorCodes.NOT_FOUND,
        'This invitation link is not valid. It may already have been used — try signing in, or ask for a new one.',
        HttpStatus.NOT_FOUND,
      );
    }
    if (invitation.expiresAt.getTime() < Date.now()) {
      throw new AppException(
        ErrorCodes.CONFLICT,
        'This invitation has expired. Ask whoever invited you to send a new link.',
        HttpStatus.CONFLICT,
      );
    }
    if (invitation.organizationMember?.status === 'REMOVED') {
      throw new AppException(
        ErrorCodes.CONFLICT,
        'This invitation was withdrawn.',
        HttpStatus.CONFLICT,
      );
    }

    /*
      "Has a usable password" is derived here rather than stored, and it is the one thing the
      accept path branches on. An account created BY an invite carries a random hash nobody
      can produce; a real account carries one its owner chose. The marker is the flag written
      at creation, not a guess about hash shape.
    */
    const hasUsablePassword = !invitation.user.passwordHash.startsWith(INVITE_PLACEHOLDER_PREFIX);
    return { ...invitation, hasUsablePassword };
  }

  /**
   * Re-issue an invitation for a member who has not accepted yet.
   *
   * Exists because every member invited before this change is sitting at INVITED with no way
   * in, and because links expire. Refused once the member is ACTIVE: there would be nothing
   * to accept, and minting a fresh credential for a live account is a way in for anybody who
   * can read the owner's screen.
   */
  async resendInvitation(user: RequestUser, orgId: string, memberId: string) {
    await this.access.assertMember(user, orgId, [Role.ORGANIZER_OWNER]);

    const member = await this.prisma.organizationMember.findUnique({
      where: { id: memberId },
      include: { user: { select: { id: true, email: true } } },
    });
    if (!member || member.organizationId !== orgId) {
      throw new AppException(ErrorCodes.NOT_FOUND, 'Team member not found.', HttpStatus.NOT_FOUND);
    }
    if (member.status === 'ACTIVE') {
      throw new AppException(
        ErrorCodes.CONFLICT,
        'This person has already joined, so there is nothing to accept.',
        HttpStatus.CONFLICT,
      );
    }

    const inviteUrl = await this.issueInvitation(member.userId, user.id, memberId);
    await this.audit.record({
      actorUserId: user.id,
      organizationId: orgId,
      action: 'MEMBER_INVITE_RESENT',
      entityType: 'OrganizationMember',
      entityId: memberId,
    });
    return { inviteUrl, email: member.user.email };
  }

  /**
   * Turn cash-at-the-venue on or off for this organization.
   *
   * Its own endpoint rather than a field on the public profile, because it is nothing like
   * a logo: switching it on means this organizer will take money the platform never sees,
   * which changes who is responsible for collecting it and what a settlement can honestly
   * promise. Owner only, and audited.
   */
  async setCashPayments(user: RequestUser, orgId: string, enabled: boolean) {
    await this.access.assertMember(user, orgId, [Role.ORGANIZER_OWNER]);

    const org = await this.prisma.organization.update({
      where: { id: orgId },
      data: { cashPaymentsEnabled: enabled },
      select: { id: true, cashPaymentsEnabled: true },
    });
    await this.audit.record({
      actorUserId: user.id,
      organizationId: orgId,
      action: enabled ? 'CASH_PAYMENTS_ENABLED' : 'CASH_PAYMENTS_DISABLED',
      entityType: 'Organization',
      entityId: orgId,
    });
    return org;
  }

  /**
   * The counter's worklist: cash bookings that have been reserved but not yet paid for.
   *
   * Ordered by when the show starts rather than when the booking was made, because the
   * person at the counter is working through tonight's audience, not a chronological log.
   */
  async cashBookings(user: RequestUser, orgId: string, includeCollected = false) {
    /*
      Check-in staff are included deliberately. At a single-screen cinema the person on the
      door is the person with the cash tin, and a worklist they cannot open is a worklist
      somebody else has to read out to them.
    */
    await this.access.assertMember(user, orgId, [
      Role.ORGANIZER_OWNER,
      Role.ORGANIZER_MANAGER,
      Role.CHECKIN_STAFF,
    ]);

    const bookings = await this.prisma.booking.findMany({
      where: {
        organizationId: orgId,
        paymentMethod: 'CASH',
        ...(includeCollected
          ? { status: { in: ['PENDING_PAYMENT', 'CONFIRMED'] } }
          : { status: 'PENDING_PAYMENT' }),
      },
      select: {
        id: true,
        reference: true,
        buyerName: true,
        buyerEmail: true,
        totalMinor: true,
        currency: true,
        status: true,
        cashCollectedAt: true,
        createdAt: true,
        cashCollectedBy: { select: { fullName: true } },
        event: { select: { title: true } },
        eventSession: { select: { startsAt: true } },
      },
      orderBy: [{ eventSession: { startsAt: 'asc' } }, { createdAt: 'asc' }],
      take: 200,
    });

    return bookings.map((b) => ({
      id: b.id,
      reference: b.reference,
      buyerName: b.buyerName,
      buyerEmail: b.buyerEmail,
      totalMinor: b.totalMinor,
      currency: b.currency,
      status: b.status,
      eventTitle: b.event.title,
      startsAt: b.eventSession.startsAt,
      collectedAt: b.cashCollectedAt,
      collectedBy: b.cashCollectedBy?.fullName ?? null,
    }));
  }

  // ─── Admin ───

  async adminList(status: OrganizationStatus | undefined, page: number, pageSize: number) {
    const where = status ? { status } : {};
    const [total, data] = await this.prisma.$transaction([
      this.prisma.organization.count({ where }),
      this.prisma.organization.findMany({
        where,
        skip: (page - 1) * pageSize,
        take: pageSize,
        orderBy: { createdAt: 'desc' },
        // `autoApproveEvents` comes back on the list so the admin queue can show which
        // organizers bypass review WITHOUT a request per row.
        include: { _count: { select: { members: true, events: true } } },
      }),
    ]);
    return { data, meta: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } };
  }

  /**
   * Let this organizer's events go live without a reviewer, or stop letting them.
   *
   * ── WHY ONLY A PLATFORM ADMIN CAN CALL THIS ────────────────────────────────────────
   * "It is hard to approve each and every event — let's have a toggle on the orgs, auto
   * approve if we are getting an event from trusted orgs. We disable auto approve for new
   * orgs or not trusted ones." Trust is the platform's judgement about the organizer, so it
   * cannot be a setting the organizer owns; a self-service version is not trust, it is a
   * checkbox that every organizer ticks on their first day.
   *
   * Two conditions beyond the permission, both making "trusted" mean something:
   *   · the organization must be APPROVED — a pending or suspended one has not earned it;
   *   · it must have had at least one event approved the ordinary way, so there is a
   *     history to have been trusted ON. This is the "not for new orgs" half of the ask,
   *     enforced rather than left to whoever is clicking.
   *
   * Turning it OFF has no conditions at all. Withdrawing trust must never be harder than
   * granting it.
   */
  async setAutoApprove(admin: RequestUser, orgId: string, enabled: boolean) {
    const org = await this.prisma.organization.findUnique({ where: { id: orgId } });
    if (!org)
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);

    if (enabled) {
      if (org.status !== OrganizationStatus.APPROVED) {
        throw new AppException(
          ErrorCodes.CONFLICT,
          `Only an approved organizer can auto-publish events (this one is ${org.status.toLowerCase()}).`,
          HttpStatus.CONFLICT,
        );
      }
      const approvedBefore = await this.prisma.event.count({
        where: { organizationId: orgId, publishedAt: { not: null } },
      });
      if (approvedBefore === 0) {
        throw new AppException(
          ErrorCodes.CONFLICT,
          'This organizer has never had an event approved. Review their first event, then turn this on.',
          HttpStatus.CONFLICT,
        );
      }
    }

    const updated = await this.prisma.organization.update({
      where: { id: orgId },
      data: { autoApproveEvents: enabled },
    });
    await this.audit.record({
      actorUserId: admin.id,
      organizationId: orgId,
      action: enabled ? 'ORG_AUTO_APPROVE_ENABLED' : 'ORG_AUTO_APPROVE_DISABLED',
      entityType: 'Organization',
      entityId: orgId,
    });
    return { id: updated.id, autoApproveEvents: updated.autoApproveEvents };
  }

  async review(admin: RequestUser, orgId: string, input: ReviewDecisionInput) {
    const org = await this.prisma.organization.findUnique({ where: { id: orgId } });
    if (!org)
      throw new AppException(ErrorCodes.NOT_FOUND, 'Organization not found.', HttpStatus.NOT_FOUND);

    const status =
      input.decision === 'APPROVE' ? OrganizationStatus.APPROVED : OrganizationStatus.REJECTED;
    const updated = await this.prisma.organization.update({
      where: { id: orgId },
      data: { status },
    });
    await this.audit.record({
      actorUserId: admin.id,
      organizationId: orgId,
      action: input.decision === 'APPROVE' ? 'ORGANIZATION_APPROVED' : 'ORGANIZATION_REJECTED',
      entityType: 'Organization',
      entityId: orgId,
      metadata: { note: input.note },
    });

    /*
      Close the loop with the organizer.

      Approval is the moment they can start selling, and rejection is the moment they need to
      know why. Neither was communicated — the status changed in a table and the person who
      had been waiting was left refreshing a page.
    */
    await this.audience.notifyOrganizationOwners(
      orgId,
      input.decision === 'APPROVE'
        ? NotificationType.ORGANIZATION_APPROVED
        : NotificationType.ORGANIZATION_REJECTED,
      { organizationId: orgId, organizationName: updated.name, reason: input.note ?? '' },
    );

    return updated;
  }
}
